Attachment Feature
apostle/apostle.py pull request #1
Opened 2017-03-31 09:36 UTC by mantishK

Added the ability to send files as attachments.

2017-04-02 23:57 UTC, snikch requested changes
Thanks for this, looks good. Just a couple of style comments but the functionality looks great 👌

2017-04-02 23:57 UTC, snikch commented on apostle/mail.py
> +            'attachments': self.attachments
Indentation here is incorrect.

2017-04-02 23:57 UTC, snikch commented on apostle/mail.py
> +		})
Please ensure there's a trailing newline at the end of the files (for consistency).

2017-04-03 03:57 UTC, mantishK commented on apostle/mail.py
> +		})
Fixed!

2017-04-03 04:03 UTC, mantishK commented
@snikch Made the review changes

2017-04-04 18:49 UTC, merged

2017-04-04 18:49 UTC, snikch commented
Great, thanks!